version: 2.1
orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6
jobs:
  Test:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install:
          install-yarn: true 
          install-npm: false
      - checkout
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Yarn test
          command: yarn test --passWithNoTests
      - run:
          name: Yarn build
          command: yarn build

  Deploy-in-develop:
    executor: heroku/default
    environment:
      HEROKU_APP_NAME: "frontend-develop"
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
workflows:
  Install-Test-Build:
    jobs:
      - Test
